name: Build ZMK firmware

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Build LEFT
        uses: zmkfirmware/zmk-docker-build@main
        with:
          board: nice_nano_v2
          shield: my_split_left
          archive-name: my_split_left-nice_nano_v2

      - name: Build RIGHT
        uses: zmkfirmware/zmk-docker-build@main
        with:
          board: nice_nano_v2
          shield: my_split_right
          archive-name: my_split_right-nice_nano_v2
